### ISSUE TITLE
relation "instance" does not exist

### ISSUE THREAD

**Issue by sglebs** [guokr/tsuru-postgresapi#6]
I followed the documented steps but I get this error when trying to create the service instance:

tsuru service-add postgresapi namoroondb

Error: Failed to create the instance namoroondb: relation "instance" does not exist
LINE 1: SELECT 1 FROM instance WHERE name='namoroondb'

Any ideas? Thanks!

**Comment by sglebs** [comment]
Any chance it is missing the database initialization step in the README? The mysqlapi seems to have the same problem in the documentation, and I was told to run:

tsuru app-run -a mysqlapi -- python manage.py syncdb --noinput

Maybe something similar is needed here?

**Comment by sroze** [comment]
@sglebs this repository was moved to Tsuru organization: https://github.com/tsuru/postgres-api

**Comment by sroze** [comment]
@philiptzou Any chance that you remove everything from here except a "redirect README" ?

**Comment by philiptzou** [comment]
@sroze Done. Thanks for reminding.
